Feature/to do list v0.3(add todolist class)
melanu1991/ToDoList pull request #9
Opened 2017-07-13 18:46 UTC by melanu1991

Второй вариант с другой архитектурой

2017-08-02 21:17 UTC, imironenko requested changes

2017-08-02 21:17 UTC, imironenko commented on ToDoList/ToDoList/VAKAddProjectViewController.m
> +    if ([self.nameProjectField.text length] > VAKZero) {
как мы можем упростить данную конструкцию, т.е. 6 строк ?

2017-08-02 21:17 UTC, imironenko commented on ToDoList/ToDoList/VAKAddTaskController.m
> +
Давай упростим конструкцию создания ячеек
1. Сделаем int enum для секций вместо констант VAKZero, VAKOne, VAKTwo и т.д. Например VAKTaskSection
2. конфигурацию каждой ячейки вынесем в отдельный метод
3. на основе enum, определим константный массив с идентификаторами row, например 
```
NSString *const VAKTaskRowIdentifierForSection[sectionCount] = [ 
[VAKSectionFirst] = @"VAKTaskNameCellIdentifier", 
[VAKSectionSecond] = @"VAKTaskRemindCellIdentifier", 
...
]
```

2017-08-02 21:17 UTC, imironenko commented on ToDoList/ToDoList/VAKAddTaskController.m
> +    if (section == VAKZero) {
преобразум данную конструкцию, используя enum, созданный выше

2017-08-02 21:17 UTC, imironenko commented on ToDoList/ToDoList/VAKAddTaskController.m
> +    [self.tableView registerNib:[UINib nibWithNibName:identifier bundle:nil] forCellReuseIdentifier:identifier];
регистрация Nib не должно быть многократно, достаточно один раз сделать

2017-08-02 21:17 UTC, imironenko commented on ToDoList/ToDoList/VAKAddTaskController.m
> +- (void)doneButtonPressed {
очень массивный метод, много чего делается, подумай как можно разбить его, 
1. выделить логические куски, 
2. не лишним будет добавить пустые строки, отделив логические части

2017-08-02 21:17 UTC, imironenko commented on ToDoList/ToDoList/VAKAddTaskController.m
> +            Date *date = (Date *)[[VAKCoreDataManager sharedManager] createEntityWithName:@"Date"];
кастомная сущность Date, давай назовем иначе, раз это core data сущеость, напр. VAKManagedData

2017-08-02 21:17 UTC, imironenko commented on ToDoList/ToDoList/VAKCoreDataManager.h
> +- (NSURL *)applicationDocumentsDirectory;
действительно ли надо, делать метод видимым извне ?

2017-08-02 21:17 UTC, imironenko commented on ToDoList/ToDoList/VAKCustumCell.m
> +- (void)awakeFromNib {
действительно ли есть надобность в этом методе или мы можем убрать его ?

2017-08-02 21:17 UTC, imironenko commented on ToDoList/ToDoList/VAKInboxViewController.m
> +- (NSString *)tableView:(UITableView *)tableView titleForHeaderInSection:(NSInteger)section {
метод вызывается многократно, излишне нагружен логикой, стоит подумать как уйти от этого

2017-08-02 21:17 UTC, imironenko commented on ToDoList/ToDoList/VAKInboxViewController.m
> +- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section {
аналогичная логика, дублированный код

2017-08-02 21:17 UTC, imironenko commented on ToDoList/ToDoList/VAKInboxViewController.m
> +- (Task *)returnSelectedTaskByIndexPath:(NSIndexPath *)indexPath {
не стоит называть так метод, префикс `return` нет нужды использовать

2017-08-02 21:17 UTC, imironenko commented on ToDoList/ToDoList/VAKSearchViewController.m
> +@property (assign, nonatomic) BOOL needToReloadData;
стоит переименовать getter

2017-08-02 21:17 UTC, imironenko commented on ToDoList/ToDoList/VAKSearchViewController.m
> +- (Task *)returnSelectedTaskByIndexPath:(NSIndexPath *)indexPath {
неккоректное наименование метода

2017-08-02 21:17 UTC, imironenko commented on ToDoList/ToDoList/VAKTodayViewController.m
> +
нет вызова супер

2017-08-02 21:17 UTC, imironenko commented on ToDoList/ToDoList/VAKTodayViewController.m
> +- (NSDate *)startCurrentDate {
корректнее `startedDate`

2017-08-02 21:17 UTC, imironenko commented on ToDoList/ToDoList/VAKTodayViewController.m
> +- (NSDate *)finishCurrentDate {
корректнее `finishedDate`

2017-08-02 21:17 UTC, imironenko commented on ToDoList/ToDoList/VAKTodayViewController.m
> +- (Task *)returnSelectedTaskByIndexPath:(NSIndexPath *)indexPath {
стоит убрать `return`

2017-08-02 21:17 UTC, imironenko commented on ToDoList/ToDoList/VAKTodayViewController.m
> +- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section {
метод сильно перегружен логикой с NSPredicate

2017-08-02 21:17 UTC, imironenko commented on ToDoList/ToDoList/VAKTodayViewController.m
> +- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
стоит сформировать необходимые массивы на старте и затем их использовать, по надобности обновлять, но не стоит фильтровать данные в данном методе

2017-08-03 10:05 UTC, melanu1991 commented on ToDoList/ToDoList/VAKAddTaskController.m
> +- (void)doneButtonPressed {
Переработан

2017-08-03 10:05 UTC, melanu1991 commented on ToDoList/ToDoList/VAKInboxViewController.m
> +- (NSString *)tableView:(UITableView *)tableView titleForHeaderInSection:(NSInteger)section {
Переработан

2017-08-03 10:05 UTC, melanu1991 commented on ToDoList/ToDoList/VAKTodayViewController.m
> +- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section {
Переработан

2017-08-03 10:07 UTC, melanu1991 commented on ToDoList/ToDoList/VAKAddProjectViewController.m
> +    if ([self.nameProjectField.text length] > VAKZero) {
На ум ничего не приходит:( Ведь нам нужно проверять после завершения ввода количество символов на неравенство нулю, если неравно кнопку делать доступной, иначе недоступной.

2017-08-08 21:05 UTC, imironenko requested changes

2017-08-08 21:05 UTC, imironenko commented on ToDoList/ToDoList/VAKAddProjectViewController.m
> +    if ([self.nameProjectField.text length] > VAKZero) {
в зависисимости от условия, делаем активной или нет кнопку, соответственно можно заменить в одну строку
`self.doneButton.enabled = ([self.nameProjectField.text length] > VAKZero);`

2017-08-08 21:05 UTC, imironenko commented on ToDoList/ToDoList/VAKAddTaskController.m
> +static NSString * const VAKTaskRowIdentifierForSection[] = { @"VAKTaskNameCell", @"VAKRemindCell", @"VAKDateCell", @"VAKPriorityCell", @"VAKNotesCell" };
сойдет, но лучше было бы привязать к enum, тем самым исключить вероятность ошибки при добавлении новой секции
```
NSString *const VAKTaskRowIdentifierForSection[sectionCount] = [ 
[VAKSectionFirst] = @"VAKTaskNameCellIdentifier", 
[VAKSectionSecond] = @"VAKTaskRemindCellIdentifier", 
...
]
```

2017-08-08 21:05 UTC, imironenko commented on ToDoList/ToDoList/VAKAddTaskController.m
> +        _priorities = [NSArray arrayWithObjects:VAKNone, VAKLow, VAKMedium, VAKHigh, nil];
аналогично cellIdentifiers

2017-08-08 21:05 UTC, imironenko commented on ToDoList/ToDoList/VAKAddTaskController.m
> +    UITableViewCell *cell = [self configurationCellForIndexPath:indexPath];
не верно, лучшим вариантом будет создать методы конфигурации для каждого типа ячейки, а здесь вызывать уже необходимый метод
```
if (indexPath.section == 0) {
  [self nameCellForIndexPath:indexPath];
} 
if (indexPath.section == 1) {
  [self remindeCellForIndexPath:indexPath];
}
else {
....

```

2017-08-08 21:05 UTC, imironenko commented on ToDoList/ToDoList/VAKCustumCell.m
> +- (void)setSelected:(BOOL)selected animated:(BOOL)animated {
действительно ли есть надобность в этом методе или мы можем убрать его ?
вопрос касается всех подобных методов :)

2017-08-08 21:05 UTC, imironenko commented on ToDoList/ToDoList/VAKAddTaskController.m
> +    return VAKFour;
возвращение данного значения не является корректным, лучше выделить отдельную константу соответствующая кол-ву секций `VAKAddTaskNumberOfSection`, тем самым, при добавлении новых секций будет необходимо изменить данное значение
также правильнее переименовать `VAKFour` = `VAKFourthSection` и аналогичные ей

2017-08-10 07:20 UTC, melanu1991 commented on ToDoList/ToDoList/VAKCustumCell.m
> +- (void)setSelected:(BOOL)selected animated:(BOOL)animated {
Ненужен) т.к. по умолчанию итак super вызывается+)

2017-08-22 11:38 UTC, imironenko approved these changes
👍

2017-08-24 10:44 UTC, merged